[tool.poetry]
name = "fake-news-detector"
version = "0.1.0"
description = "Project to detect fake news."
authors = ["Oliver <antonioj.oliver.garcia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scikit-learn = "^1.5.2"
matplotlib = "^3.9.2"
<<<<<<< HEAD
mlflow = "^2.17.2"
=======
jupyter = "^1.1.1"
pandas = "~2.0"
numpy = "~1.25"
nltk = "^3.9.1"
gensim = "^4.3.3"
>>>>>>> 8a7ce7d (ğŸ“ Convert text to vectors and train the model)


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
